import { getPublicPageSeo } from "@/features/website/seo/routes";
import { JsonLd } from "@/features/website/seo/json-ld";
import { Cta, SectionIntro } from "@/features/website/components";
import { t, type Locale } from "@/features/website/content";
export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }) {
  return (await getPublicPageSeo("about", (await params).locale)).metadata;
}

export default async function About({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const seo = await getPublicPageSeo("about", locale); const label = (id: string, en: string) => t(locale, id, en); return <><JsonLd data={seo.schema} /><section className="section-space border-b"><div className="site-shell"><SectionIntro kicker="ABOUT LUNABINER" title={label("Kami ada untuk membantu bisnis bekerja lebih cerdas.", "We exist to help businesses work smarter.")} body={label("LunaBiner adalah partner teknologi yang menghubungkan software, automation, data, dan AI menjadi solusi yang praktis bagi operasi bisnis.", "LunaBiner is a technology partner that connects software, automation, data, and AI into practical solutions for business operations.")} /></div></section><section className="section-space"><div className="site-shell grid gap-12 lg:grid-cols-2"><div><p className="section-kicker">OUR STORY</p><h2 className="display-title mt-4 text-3xl">{label("Teknologi yang terasa jelas dan manusiawi.", "Technology that feels clear and human.")}</h2></div><p className="max-w-xl leading-8 text-[#64767B]">{label("Nama LunaBiner terinspirasi oleh nilai kepedulian, arahan, perlindungan, dan pertumbuhan. Nilai itu membentuk cara kami bekerja: memahami masalah sebelum memilih teknologi, lalu membangun sesuatu yang dapat dipakai dan dikembangkan tim Anda.", "The LunaBiner name is inspired by care, guidance, protection, and growth. Those values shape how we work: understand the problem before selecting technology, then build something your team can use and grow with.")}</p></div></section><section className="section-space bg-[#EAF5F4]"><div className="site-shell"><SectionIntro kicker="HOW WE THINK" title={label("Prinsip yang menjaga setiap keputusan tetap relevan.", "Principles that keep every decision relevant.")} /><div className="mt-12 grid gap-4 md:grid-cols-4">{[["Business first", "Solve the business problem before choosing technology."], ["Connected by design", "Design systems and information flows together."], ["Built to scale", "Leave room for the next stage of growth."], ["Partner over handoff", "Continue to improve after launch."]].map(([title, text]) => <div className="rounded-xl bg-white p-5" key={title}><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#64767B]">{text}</p></div>)}</div></div></section><Cta locale={locale} /></>; }
