import { getCaseStudySeoContent } from "@/features/website/seo/content";
import { publicSeoLocale } from "@/features/website/seo/routes";
import { buildSeo } from "@/features/website/seo";
import { JsonLd } from "@/features/website/seo/json-ld";
import Link from "next/link";
import { PublishedDetail } from "@/features/cms/public";
import { ArrowRight } from "lucide-react";
import { Cta } from "@/features/website/components";
import { t, type Locale } from "@/features/website/content";
import { notFound } from "next/navigation";
export async function generateMetadata({ params }: { params: Promise<{ locale: Locale; id: string }> }) {
  const values = await params;
  const content = await getCaseStudySeoContent(publicSeoLocale(values.locale), values.id);
  if (!content) notFound();
  return buildSeo(content.seo).metadata;
}
export default async function CaseStudy({ params }: { params: Promise<{ locale: Locale; id: string }> }) { const values = await params; const locale = publicSeoLocale(values.locale); const content = await getCaseStudySeoContent(locale, values.id); if (!content) notFound(); const seo = buildSeo(content.seo); if (content.entry) return <><JsonLd data={seo.schema} /><PublishedDetail entry={content.entry} locale={locale} /><Cta locale={locale} /></>; const project = content.project; if (!project) notFound(); const label = (idn: string, en: string) => t(locale, idn, en); return <><JsonLd data={seo.schema} /><section className={`bg-gradient-to-br ${project.tone} py-20 text-white sm:py-28`}><div className="site-shell"><p className="text-xs font-bold tracking-[.18em] text-white/70">{label("CONTOH ILUSTRATIF", "ILLUSTRATIVE EXAMPLE")} / {project.industry[locale]}</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">{project.title[locale]}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/85">{project.solution[locale]}</p></div></section><article className="section-space"><div className="site-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><aside><p className="section-kicker">OVERVIEW</p><dl className="mt-6 grid gap-5 text-sm"><div><dt className="text-[#64767B]">{label("Industri", "Industry")}</dt><dd className="mt-1 font-semibold">{project.industry[locale]}</dd></div><div><dt className="text-[#64767B]">{label("Kemampuan", "Capabilities")}</dt><dd className="mt-2 flex flex-wrap gap-2">{project.capabilities.map((item) => <span key={item} className="rounded-full border px-3 py-1">{item}</span>)}</dd></div></dl></aside><div className="grid gap-10"><Detail title={label("Tantangan bisnis", "Business challenge")} text={project.problem[locale]} /><Detail title={label("Pendekatan", "Approach")} text={label("Kami memetakan alur kerja, titik pertukaran data, dan keputusan yang perlu didukung sistem sebelum merancang solusi.", "We mapped the workflows, data handoffs, and decisions the system needed to support before designing the solution.")} /><Detail title={label("Solusi", "Solution")} text={project.solution[locale]} /><Detail title={label("Dampak", "Impact")} text={project.impact[locale]} /><div className="rounded-2xl bg-[#EAF5F4] p-7"><p className="text-sm font-semibold">{label("Siap membahas tantangan serupa?", "Facing a similar challenge?")}</p><Link href={`/${locale}/contact`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#08747A]">{label("Hubungi kami", "Talk to us")} <ArrowRight size={16} /></Link></div></div></div></article><Cta locale={locale} /></>; }
function Detail({ title, text }: { title: string; text: string }) { return <section><h2 className="text-2xl font-semibold tracking-[-.03em]">{title}</h2><p className="mt-4 max-w-2xl leading-7 text-[#64767B]">{text}</p></section>; }
