import { ArticleGrid, Cta, SectionIntro, ServiceGrid, WorkGrid } from "@/features/website/components";
import { t, type Locale } from "@/features/website/content";
import { ArrowDown, ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";

export default async function Home({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; const label = (id: string, en: string) => t(locale, id, en);
  const problems = locale === "id" ? ["Proses manual", "Sistem terpisah", "Pekerjaan berulang", "Data tersebar", "Keputusan lambat", "AI tanpa use case jelas"] : ["Manual processes", "Disconnected systems", "Repetitive work", "Scattered data", "Slow decisions", "AI without a clear use case"];
  return <>
    <section className="relative overflow-hidden border-b bg-[#F8FAFA]"><div className="site-shell grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-24"><div><p className="section-kicker">SOFTWARE + AUTOMATION + DATA + AI</p><h1 className="display-title mt-5 max-w-3xl text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">{label("Bangun sistem digital yang lebih cerdas untuk bisnis Anda.", "Build smarter digital systems for your business.")}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#64767B]">{label("LunaBiner menghubungkan software, automation, data, dan AI untuk membantu bisnis bekerja lebih efektif dan berkembang lebih cepat.", "LunaBiner combines software, automation, data and AI to help businesses operate smarter and scale faster.")}</p><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 rounded-full bg-[#F5A033] px-6 py-3.5 text-sm font-semibold text-[#132A32] hover:bg-[#DD841C]" href={`/${locale}/contact`}>{label("Mulai proyek", "Start a project")} <ArrowRight size={16} /></Link><Link className="inline-flex items-center gap-2 rounded-full border bg-white px-6 py-3.5 text-sm font-semibold text-[#132A32] hover:border-[#18B7B3]" href={`/${locale}/work`}>{label("Lihat portfolio", "Explore our work")}</Link></div></div><div className="relative mx-auto flex aspect-square w-full max-w-md items-center justify-center"><div className="absolute inset-[7%] rounded-full border border-[#63CEC9]" /><div className="absolute inset-[17%] rounded-full border-[20px] border-[#0F8F95]/15" /><div className="relative grid h-44 w-44 place-items-center rounded-full bg-[#08747A] text-center text-lg font-semibold text-white shadow-[0_0_0_18px_rgba(24,183,179,.15)]">Smarter<br />Business</div><div className="absolute right-2 top-[15%] grid h-16 w-16 place-items-center rounded-full bg-[#F5A033] text-xs font-bold text-[#132A32]">AI</div><div className="absolute bottom-[10%] left-[4%] rounded-xl bg-white p-4 text-sm font-semibold shadow-lg">Connected<br /><span className="text-[#08747A]">systems</span></div></div></div><div className="site-shell pb-8"><a href="#problems" className="inline-flex items-center gap-2 text-sm font-medium text-[#64767B]"><ArrowDown size={16} /> {label("Jelajahi bagaimana kami bekerja", "Explore how we work")}</a></div></section>
    <section className="border-b bg-white"><div className="site-shell grid gap-7 py-9 text-sm sm:grid-cols-3"><p className="font-semibold">{label("Dirancang untuk bisnis yang sedang bertumbuh", "Designed for growing businesses")}</p><p className="text-[#64767B]">{label("Dari proses manual menuju sistem yang terhubung", "From manual processes to connected systems")}</p><p className="text-[#64767B]">{label("Pendekatan bisnis dulu, teknologi kemudian", "Business first, technology second")}</p></div></section>
    <section id="problems" className="section-space"><div className="site-shell grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><SectionIntro kicker="WHAT WE SOLVE" title={label("Masalah bisnis tidak harus menjadi pekerjaan manual.", "Business problems do not have to become manual work.")} body={label("Kami membantu tim memetakan hambatan operasional dan membentuk solusi digital yang terhubung.", "We help teams map operational friction and shape connected digital solutions.")} /><div className="grid gap-3 sm:grid-cols-2">{problems.map((item, i) => <div className="rounded-xl border bg-white p-5" key={item}><span className="text-xs font-bold text-[#F5A033]">0{i + 1}</span><p className="mt-5 font-semibold">{item}</p></div>)}</div></div></section>
    <section className="section-space bg-[#EAF5F4]"><div className="site-shell"><SectionIntro kicker="SOLUTIONS" title={label("Kemampuan yang bekerja sebagai satu solusi.", "Capabilities that work as one solution.")} body={label("Setiap layanan dapat berdiri sendiri, namun kami merancangnya agar saling memperkuat.", "Every service can stand alone, but we design them to reinforce one another.")} /><div className="mt-12"><ServiceGrid locale={locale} /></div></div></section>
    <section className="section-space bg-[#132A32]"><div className="site-shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker !text-[#63CEC9]">CONNECTED TECHNOLOGY</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] text-white sm:text-5xl">{label("Satu solusi yang terhubung untuk bisnis Anda.", "One connected solution for your business.")}</h2></div><div className="grid gap-2 sm:grid-cols-5">{["Software", "Automation", "Data", "AI"].map((x, index) => <div className="rounded-xl border border-white/15 bg-white/5 p-4 text-center text-sm font-semibold text-white" key={x}>{x}{index < 3 && <span className="hidden text-[#63CEC9] sm:block">↓</span>}</div>)}<div className="rounded-xl bg-[#F5A033] p-4 text-center text-sm font-bold text-[#132A32]">Smarter<br />Business</div></div></div></section>
    <section className="section-space bg-white"><div className="site-shell"><div className="flex flex-wrap items-end justify-between gap-6"><SectionIntro kicker="SELECTED WORK" title={label("Dibangun untuk konteks bisnis nyata.", "Built for real business contexts.")} /><Link className="text-sm font-semibold text-[#08747A]" href={`/${locale}/work`}>{label("Semua portfolio", "All work")} →</Link></div><div className="mt-12"><WorkGrid locale={locale} /></div></div></section>
    <section className="section-space"><div className="site-shell"><SectionIntro kicker="HOW WE WORK" title={label("Jelas dari masalah sampai perbaikan berkelanjutan.", "Clear from problem to continuous improvement.")} /><div className="mt-12 grid gap-3 md:grid-cols-5">{[["01", "Understand", "Business problem & process"], ["02", "Design", "Solution & architecture"], ["03", "Build", "Software, automation & AI"], ["04", "Integrate", "Systems & data"], ["05", "Improve", "Measure, support & iterate"]].map(([no, title, body]) => <div className="border-t-2 border-[#18B7B3] pt-5" key={no}><p className="text-xs font-bold text-[#F5A033]">{no}</p><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#64767B]">{body}</p></div>)}</div></div></section>
    <section className="section-space bg-[#EAF5F4]"><div className="site-shell grid gap-12 lg:grid-cols-2"><SectionIntro kicker="WHY LUNABINER" title={label("Teknologi yang berpihak pada cara bisnis Anda berkembang.", "Technology that serves the way your business grows.")} /><div className="grid gap-5 sm:grid-cols-2">{[["Business First", "We solve the business problem before choosing technology."], ["Connected Solutions", "Software, automation, data and AI designed as one system."], ["Built to Scale", "Solutions designed for future growth."], ["Long-Term Partnership", "From discovery through continuous improvement."]].map(([title, body]) => <div key={title} className="rounded-xl bg-white p-5"><CheckCircle2 className="text-[#08747A]" size={20} /><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#64767B]">{body}</p></div>)}</div></div></section>
    <section className="section-space bg-[#132A32]"><div className="site-shell grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="section-kicker !text-[#63CEC9]">AI FOR REAL BUSINESS</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] text-white sm:text-5xl">{label("AI seharusnya menyelesaikan masalah bisnis, bukan menjadi eksperimen baru.", "AI should solve business problems, not become another experiment.")}</h2></div><div className="grid gap-3 sm:grid-cols-2">{[["Knowledge", "AI Assistant"], ["Documents", "Document Intelligence"], ["Process", "AI Automation"], ["Data", "Business Insight"]].map(([from, to]) => <div className="rounded-xl border border-white/15 bg-white/5 p-5" key={from}><p className="text-sm text-[#C7D7D7]">{from}</p><p className="my-2 text-[#63CEC9]">↓</p><p className="font-semibold text-white">{to}</p></div>)}</div></div></section>
    <section className="section-space bg-[#EAF5F4]"><div className="site-shell grid gap-8 rounded-3xl bg-white p-8 md:grid-cols-[1.3fr_.7fr] md:p-12"><div><p className="section-kicker">LUNABINER LABS</p><h2 className="display-title mt-4 text-3xl sm:text-4xl">{label("Membayangkan produk yang membantu bisnis di tahap berikutnya.", "Imagining products that support the next stage of business.")}</h2><p className="mt-5 max-w-xl leading-7 text-[#64767B]">{label("Eksplorasi LunaBiner untuk komunikasi privat organisasi dan pengelolaan cashflow yang lebih cerdas.", "LunaBiner explorations for private organizational communication and smarter cashflow management.")}</p></div><div className="grid content-center gap-3"><Link href={`/${locale}/products`} className="rounded-xl border p-4 text-sm font-semibold transition hover:border-[#18B7B3]">Enterprise Chat <span className="float-right text-[#08747A]">→</span></Link><Link href={`/${locale}/products`} className="rounded-xl border p-4 text-sm font-semibold transition hover:border-[#18B7B3]">AI Cashflow <span className="float-right text-[#08747A]">→</span></Link></div></div></section>
    <section className="section-space bg-white"><div className="site-shell"><SectionIntro kicker="INSIGHTS" title={label("Perspektif praktis tentang teknologi dan bisnis.", "Practical perspectives on technology and business.")} /><div className="mt-12"><ArticleGrid locale={locale} /></div></div></section><Cta locale={locale} />
  </>;
}
