import Link from "next/link";
import { db } from "@/lib/db";
import { publicContentWhere, presentContent } from "@/features/cms/service";
import { PublishedDetail } from "@/features/cms/public";
import { ArrowLeft } from "lucide-react";
import { Cta } from "@/features/website/components";
import { type Locale, website } from "@/features/website/content";
import { notFound } from "next/navigation";
export default async function Article({ params }: { params: Promise<{ locale: Locale; slug: string }> }) { const { locale, slug } = await params; const row = await db.contentEntry.findFirst({ where: { ...publicContentWhere("ARTICLE"), slug } }); if (row) return <><PublishedDetail entry={presentContent(row)} locale={locale} /><Cta locale={locale} /></>; const article = website.articles.find(x => x.slug === slug); if (!article) notFound(); return <><article className="section-space"><div className="site-shell max-w-4xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-[#08747A]" href={`/${locale}/insights`}><ArrowLeft size={16} /> Insights</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.18em] text-[#08747A]">{article.category}</p><h1 className="display-title mt-5 max-w-3xl text-4xl leading-tight sm:text-6xl">{article.title[locale]}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-[#64767B]">{article.excerpt[locale]}</p><div className="mt-14 max-w-2xl space-y-6 leading-8 text-[#42565B]"><p>{locale === "id" ? "Keputusan teknologi yang baik dimulai dari memahami cara kerja bisnis hari ini. Sebelum memilih alat atau platform, tim perlu mengetahui proses mana yang menyita waktu, informasi apa yang dibutuhkan, dan hasil seperti apa yang ingin dicapai." : "Good technology decisions begin by understanding how the business works today. Before selecting tools or platforms, teams need to know which processes consume time, what information is needed, and what outcome they want to achieve."}</p><h2 className="text-2xl font-semibold text-[#132A32]">{locale === "id" ? "Mulai dari konteks" : "Start with context"}</h2><p>{locale === "id" ? "Mulailah dengan satu masalah yang cukup spesifik untuk diuji. Setelah alur dan data dasar jelas, solusi dapat dikembangkan secara bertahap tanpa menambah kerumitan yang belum diperlukan." : "Begin with one problem specific enough to test. Once the workflow and basic data are clear, the solution can grow in stages without adding complexity that is not yet needed."}</p></div></div></article><Cta locale={locale} /></>; }
