"use client";
import {useActionState,useState} from "react";
import {t,type Locale} from "@/features/website/content";
import {bookConsultationAction,createSlotAction,cancelBookingAction,withdrawSlotAction,type BookingState} from "./actions";
import {consultationServices} from "./schema";
type Slot={id:string;startsAt:string;endsAt:string;service:string};
const display=(date:string,zone:string,locale:Locale)=>new Intl.DateTimeFormat(locale==="id"?"id-ID":"en-GB",{dateStyle:"full",timeStyle:"short",timeZone:zone}).format(new Date(date));
const localDate=(date:string,zone:string)=>new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:zone}).format(new Date(date));
export function BookingForm({locale,slots}:{locale:Locale;slots:Slot[]}){
  const[state,action,pending]=useActionState(bookConsultationAction,{message:""});
  const[service,setService]=useState("unsure"),[timezone,setTimezone]=useState("Asia/Jakarta"),[date,setDate]=useState("");
  const relevant=slots.filter(slot=>slot.service==="any"||slot.service===service);
  const dates=[...new Set(relevant.map(slot=>localDate(slot.startsAt,timezone)))];
  const zones=[...new Set(["Asia/Jakarta","Asia/Makassar","Asia/Jayapura","UTC",...(typeof Intl.supportedValuesOf==="function"?Intl.supportedValuesOf("timeZone"):[])])];
  const label=(id:string,en:string)=>t(locale,id,en);
  if(state.success)return <div className="rounded-2xl border bg-white p-6 sm:p-8" role="status"><h2 className="text-2xl font-semibold">{label("Jadwal tersimpan","Consultation reserved")}</h2><p className="mt-4 leading-7">{state.message}</p>{state.startsAt&&<p className="mt-4 font-medium">{display(state.startsAt,state.timezone!,locale)} · {state.timezone}</p>}<a href={state.calendarUrl} download referrerPolicy="no-referrer" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-[#F5A033] px-5 py-3 font-semibold">{label("Unduh undangan kalender","Download calendar invitation")}</a><p className="mt-4 text-sm text-slate-600">{label("Simpan undangan sekarang. Undangan tidak dikirim otomatis melalui email.","Save this invitation now. It is not automatically emailed.")}</p></div>;
  return <form action={action} className="space-y-5 rounded-2xl border bg-white p-5 shadow-sm sm:p-8"><input type="hidden" name="language" value={locale}/><label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
    <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">1. {label("Pilih layanan","Select service")}<select name="service" className="input" value={service} onChange={event=>{setService(event.target.value);setDate("");}}>{consultationServices.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-medium">{label("Zona waktu","Timezone")}<select name="timezone" className="input" value={timezone} onChange={event=>{setTimezone(event.target.value);setDate("");}}>{zones.map(zone=><option key={zone}>{zone}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-medium">2. {label("Pilih tanggal","Select date")}<select required className="input" value={date} onChange={event=>setDate(event.target.value)}><option value="">{label("Pilih tanggal tersedia","Choose an available date")}</option>{dates.map(day=><option key={day}>{day}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-medium">3. {label("Pilih waktu","Select time")}<select required name="slotId" className="input" key={`${date}-${service}-${timezone}`} defaultValue=""><option value="">{label("Pilih slot","Choose a slot")}</option>{relevant.filter(slot=>date&&localDate(slot.startsAt,timezone)===date).map(slot=><option key={slot.id} value={slot.id}>{display(slot.startsAt,timezone,locale)} · {(new Date(slot.endsAt).getTime()-new Date(slot.startsAt).getTime())/60000} min</option>)}</select></label></div>
    {!relevant.length&&<p className="text-sm text-slate-600">{label("Belum ada slot. Hubungi tim melalui halaman kontak untuk pengaturan waktu.","No slots are available. Contact the team to arrange a time.")}</p>}
    <div className="grid gap-5 sm:grid-cols-2">{[["name",label("Nama","Name"),"text",true],["company",label("Perusahaan","Company"),"text",false],["email","Email","email",true],["phone",label("Telepon","Phone"),"tel",false]].map(([name,title,type,required])=><label key={String(name)} className="grid gap-2 text-sm font-medium">4. {title}<input name={String(name)} type={String(type)} required={Boolean(required)} maxLength={name==="email"?254:name==="phone"?30:name==="name"?100:120} defaultValue={(state as BookingState).form?.[name as "name"|"company"|"email"|"phone"] ?? ""} className="input"/></label>)}</div>
    <label className="grid gap-2 text-sm font-medium">{label("Topik dan tantangan bisnis","Topic and business challenge")}<textarea required name="topic" minLength={10} maxLength={2000} defaultValue={(state as BookingState).form?.topic ?? ""} className="input min-h-28"/></label>
    <label className="flex min-h-11 items-start gap-3 text-sm"><input required name="consent" type="checkbox" className="mt-1"/>{label("Saya setuju data disimpan untuk konsultasi dan tim LunaBiner menghubungi saya.","I agree to store this information for the consultation and be contacted by LunaBiner.")}</label><p role="status" className="text-sm">{state.message}</p><button disabled={pending||!relevant.length} className="min-h-11 rounded-full bg-[#F5A033] px-6 py-3 font-semibold disabled:opacity-50">{pending?label("Menyimpan…","Reserving…"):label("Konfirmasi konsultasi","Confirm consultation")}</button>
  </form>;
}
export function SlotForm(){const[state,action,pending]=useActionState(createSlotAction,{message:""});return <form action={action} className="card space-y-4"><h2 className="font-semibold">Tambah ketersediaan</h2><label className="grid gap-2 text-sm">Mulai (UTC, bukan waktu lokal)<input required type="datetime-local" name="startsAt" className="input"/></label><label className="grid gap-2 text-sm">Durasi (menit)<input required type="number" min={15} max={120} defaultValue={30} name="duration" className="input"/></label><label className="grid gap-2 text-sm">Layanan<select name="service" className="input">{["any",...consultationServices].map(item=><option key={item}>{item}</option>)}</select></label><p role="status" className="text-sm">{state.message}</p><button disabled={pending} className="min-h-11 rounded-lg bg-[#08747A] px-5 py-3 text-white">Tambah slot</button></form>;}
export function CancelBooking({id,version}:{id:string;version:number}){const[state,action,pending]=useActionState(cancelBookingAction,{message:""});return <form action={action}><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><button disabled={pending||state.success} className="mt-3 min-h-11 rounded-lg border px-4 py-2">Batalkan booking</button><p role="status" className="mt-2 text-sm">{state.message}</p></form>;}
export function WithdrawSlot({id}:{id:string}){const[state,action,pending]=useActionState(withdrawSlotAction,{message:""});return <form action={action}><input type="hidden" name="id" value={id}/><button disabled={pending||state.success} className="min-h-11 rounded-lg border px-4 py-2">Tarik slot</button><p role="status" className="mt-2 text-sm">{state.message}</p></form>;}
